name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: EasyDesk/action-dotnet-build@v4
        with:
          build-args: -v normal
          build-configuration: Release
          path: ./<project-name>/
          warnings-as-errors: true
